const projects = [

    {
      "id": 1,
      "key": 1,
      "project_title": "Project 1",
      "subtitle": "Doggo",
      "major_category": "Frontend",
      "category_1": "web",
      "category_2": "JSON",
      "category_3": "Design",
      "image":  "/project_images/no_image.png",
      "mobile_writeup":  "Embark on a mesmerizing Code Journey! Dive into a realm where lines of code weave magic, turning dreams into digital reality. With a passion for innovation and an eye for detail, Code Journey is your gateway to captivating user experiences and groundbreaking solutions. From sleek web designs to robust applications, every project is a testament to creativity and technical prowess. Join me on this exhilarating journey of turning ideas into impactful digital experiences. Let's craft the future, one line of code at a time!",
      "technologies" : [
        "Tailwind Css",
        "Css3",
        "Html",
        "Next.js",
      ],
      "process_and_approach" : "Begin by thoroughly understanding the requirements , Identify the key objectives, target audience, and desired outcomes for the frontend mentor task. Translating the wireframes and mockups into actual design implementations using HTML, CSS, and JavaScript, also ensuring consistency across different screen sizes and devices.. Lastly, thoroughly test the frontend mentor task across multiple browsers and devices to ensure cross-browser compatibility and responsiveness. Conduct usability testing to gather feedback from potential users and identify any usability issues. ",
      "research_phase": "Requirements were given out by the task to achieve the closest replica ",
      "Development_phase": "Development commenced with the use of next.js and its sub-languages",
      "Design_phase": "Aside given properties such as images and others, a prototype was built using figma",

    },
  
    {
        "id": 2,
        "key": 2,
        "project_title": "Project 4",
        "subtitle": "Simple Ui",
        "major_category": "Frontend",
        "category_1": "web",
        "category_3": "Design",
        "mobile_writeup":  "A simple design page gotten from frontend mentor.io. The task was to replicate a design page with some giving properties using html and css",
        "image":  "/project_images/simple_ui_image.jpg",

    },
  
    {
        "id": 3,
        "key": 3,
        "project_title": "Project 3",
        "subtitle": "Calculator",
        "major_category": "Frontend",
        "category_1": "Design",
        "category_2": "Web",
        "mobile_writeup":  "A simple captivating calculator web app with basic and some advanced functions",
        "image":  "/project_images/no_image.png",
    },
  
    {
        "id": 4,
        "key": 4,
        "project_title": "Project 4",
        "subtitle": "Code journey",
        "major_category": "Frontend",
        "category_1": "web",
        "category_2": "Json",
        "category_3": "Design",
        "mobile_writeup":  "Welcome to Code Journey, where every line of code is a step toward innovation and creativity. Embark on an exhilarating adventure through the digital realm, where dreams become reality with the stroke of a keyboard. Discover captivating projects, from sleek designs to groundbreaking applications, each a testament to our passion for crafting memorable user experiences.",
        "image":  "/project_images/no_image.png",
    },
  
    {
        "id": 5,
        "key": 5,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    },
  
    {
        "id": 6,
        "key": 6,
        "project_title": "Project 6",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    },
  
    {
        "id": 7,
        "key": 7,
        "project_title": "Project 7",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "web",
        "category_2": "Design",
        "category_3": "Piece",
        "image":  "/project_images/no_image.png",
    },
  
    {
        "id": 8,
        "key": 8,
        "project_title": "Project 8",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "web",
        "category_2": "Design",
        "category_3": "Development",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 9,
        "key": 9,
        "project_title": "Project 9",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "web",
        "category_2": "Design",
        "category_3": "Development",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 10,
        "key": 10,
        "project_title": "Project 10",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "web",
        "category_2": "Design",
        "category_3": "Development",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 11,
        "key": 11,
        "project_title": "Project 11",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "web",
        "category_2": "Design",
        "category_3": "Development",
        "image":  "/project_images/no_image.png",
    },
  
    {
        "id": 12,
        "key": 12,
        "project_title": "Project 12",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Backend",
        "category_1": "web",
        "category_2": "Design",
        "category_3": "Development",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 13,
        "key": 13,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    }, 

    {
        "id": 14,
        "key": 14,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 15,
        "key": 15,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 16,
        "key": 16,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 17,
        "key": 17,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    },

    {
        "id": 18,
        "key": 18,
        "project_title": "Project 5",
        "subtitle": "lorem ipsum dolor amet sit",
        "major_category": "Fullstack",
        "category_1": "Design",
        "category_2": "Api",
        "category_3": "interactive",
        "image":  "/project_images/no_image.png",
    }

  ]
  
  export default projects